### ISSUE TITLE
Project no longer maintained?

### ISSUE THREAD

**Issue by nicholasserra** [revsys/django-tos#10]
Hello. Using this in a project, and noticed that it hasn't had activity in a while. Is this project still being maintained? Do you need additional contributors? I'd love to get some fixes in for later Django versions, thanks!

**Comment by frankwiles** [comment]
Hi Nick, 

I've most definitely fallen behind on maintenance of this project a couple others honestly.  I'll make some time early next week to clean up whatever PRs are here and would most definitely welcome some additional help!

**Comment by nicholasserra** [comment]
Awesome, thank you. I can try to issue some PRs to get the newer Django versions working. Not sure how comfortable you are with adding strangers as collaborators, but that's a possibility too. Thanks!

**Comment by frankwiles** [comment]
Awesome.  Happy to add you after a couple of PRs if that is cool with you.

**Comment by nicholasserra** [comment]
Absolutely :)
