### ISSUE TITLE
New version and PyPI release

### ISSUE THREAD

**Issue by nicholasserra** [revsys/django-tos#17]
Now that Django 1.9 compatibility has landed we could use a new version and release to PyPI

**Comment by nicholasserra** [comment]
@frankwiles Frank, when you have time, could I get a version bump and pypi release of this? Actually waiting on 1.9 compat in another project :)

**Comment by frankwiles** [comment]
Just released django-tos-0.5.0 thanks for all your hard work!

**Comment by nicholasserra** [comment]
Thanks!
