### ISSUE TITLE
PyPI version does not contain migrations

### ISSUE THREAD

**Issue by george-silva** [revsys/django-tos#19]
Hello @frankwiles ! Hello all!

The version in PyPI does not contain migrations. I'm running a very unusual setup, with django-tenants and we spent a little while trying to debug a weird error while creating a new tenant, that came from django-tos.

I had installed tos from the repository and someone else from PyPI. The error was present on his machine, because in PyPI we don't have migrations on TOS, while here worked fine.

Can we get a new release on PyPI, just to make sure everything consistent?

**Comment by nicholasserra** [comment]
+1

**Comment by frankwiles** [comment]
That's odd.  I checked django-0.5.0.tar.gz and it had the migrations in it.  I just bumped it to 0.6.0 and made a release just in case.
