### ISSUE TITLE
Django TOS allows custom users but not totally

### ISSUE THREAD

**Issue by azk4n** [revsys/django-tos#20]
In the UserAgreement model we have a unicode method that is specifically asking for user.username field.

Not all custom users have user.username fields. In our case, we have something like that, but this should be configurable and respect the settings in the custom models.

example:

```
class UserAgreement(BaseModel):
    terms_of_service = models.ForeignKey(TermsOfService, related_name='terms')
    user = models.ForeignKey(get_fk_user_model(), related_name='user_agreement')

    def __unicode__(self):
        username_field = get_user_model().USERNAME_FIELD
        if username_field:
            return u'%s agreed to TOS: %s' % (getattr(self.user, username_field),
                                              unicode(self.terms_of_service))
        else:
            return u'%s agreed to TOS: %s' % (self.user,
                                              unicode(self.terms_of_service))
```

In this case, if the model has the username field, it will use that, as you intented. If not, it will use the user's unicode.

**Comment by nicholasserra** [comment]
Seems we could also just change `self.user.username` to `unicode(self.user)` and let the end user decide how the user object is displayed as a string.

**Comment by azk4n** [comment]
yeah, it's a way.. 

thx bro!
