### ISSUE TITLE
UserAgreementMiddleware does not redirect to tos_check_url

### ISSUE THREAD

**Issue by uishnik** [revsys/django-tos#23]
The UserAgreementMiddleware has the following lines:
```
if not user_agreed:
    return add_never_cache_headers(HttpResponseRedirect(tos_check_url))
```

But add_never_cache_headers does not return anything and middleware returns None.
Maybe there should be something like this:
```
if not user_agreed:
    response = HttpResponseRedirect(tos_check_url)
    add_never_cache_headers(response)
    return response
```

**Comment by nicholasserra** [comment]
Yeah, I think you're right. PRs are welcome on this. Hopefully have time to make this fix soon.
