### ISSUE TITLE
Can't accept TOS when using cache approach

### ISSUE THREAD

**Issue by fernandoPardo** [revsys/django-tos#26]
Hi , I'm using version 0.7.1 and getting the following error when using "Option 2 (Cache Approach)" as described in the guide.

```
KeyError at /terms-of-service/confirm/
'tos_user'
```

In views.py :
https://github.com/revsys/django-tos/blob/master/tos/views.py#L119

The only place where I've seen that session variable being set is in that same file but here : 
https://github.com/revsys/django-tos/blob/master/tos/views.py#L119

It seems like the cache should be queried as well ? 

Thanks

**Comment by nicholasserra** [comment]
My assumption is that you're hitting this line:

https://github.com/revsys/django-tos/blob/7eb111dbfb24bbc7dca3d417189d644726f53b2b/tos/views.py#L56

Curious what your cache backend is set to? 

A full traceback would help too :) Thanks for the report!

**Comment by yrchen** [comment]
@fernandoPardo If you use django-tos in your middleware, you need to add the keys 'tos_user' and 'tos_backend' into your sessions after login by your own.

https://github.com/revsys/django-tos/blob/7eb111dbfb24bbc7dca3d417189d644726f53b2b/tos/views.py#L119
https://github.com/revsys/django-tos/blob/7eb111dbfb24bbc7dca3d417189d644726f53b2b/tos/views.py#L124

**Comment by fernandoPardo** [comment]
@nicholasserra  : Yup I was hitting that exact line.  The cache backend I used was Memcached. 
What @yrchen makes sense since those variables aren't set anywhere in the pluigin . Maybe I missed that in the README . If it's not there maybe it woudl be a good idea to add it

**Comment by nicholasserra** [comment]
Well it also kinda feels like a bug in the middleware. A possible patch would be to set those required session variables in the middleware if they don't exist. I'll try to get a patch in and some extra test coverage around that case.

**Comment by fernandoPardo** [comment]
Thanks for taking a look at this !
