### ISSUE TITLE
Add version 0.8.0 to PyPI

### ISSUE THREAD

**Issue by magyarn** [revsys/django-tos#39]
Hello, thank you for creating and maintaining this project. I am currently unable to install the latest version of it, 0.8.0, via pip. Running `pip install django-tos` retrieves version 0.7.2, which [PyPI](https://pypi.org/project/django-tos/) claims is most recent. Can you please update PyPI?

**Comment by nicholasserra** [comment]
Hey @magyarn, you're correct that the latest version hasn't been released. Maybe @frankwiles can do a pypi release whenever he has a second, or another member of the revsys team.

Thanks!

**Comment by goromachine** [comment]
Any update on this?
thank you

**Comment by frankwiles** [comment]
Apologies for the delay on this.  Uploaded 0.8.0 and 0.8.1 with github actions support just now.
