### ISSUE TITLE
Need to restart the server every time a user accept or reject the TOS

### ISSUE THREAD

**Issue by goromachine** [revsys/django-tos#43]
If I start the server and log in with a user that didn't accept or reject the TOS before, it just became on a loop at the /confirm/ page.
![image](https://user-images.githubusercontent.com/12257503/88822453-2a32f800-d1c4-11ea-9d8b-56af00780b69.png)

As seen on the image, it makes the redirect but it keeps making the redirect to the TOC acceptance page.

If I restar the server it stops doing that and works fine for the previously accepted users. Maybe I configured something wrong?

Thank you

**Comment by nicholasserra** [comment]
Did you figure this one out?

**Comment by goromachine** [comment]
No, this is still happening to me.

the basic use case is:
Register a new user (Django allauth used here), then it redirects to the accept terms and conditions acceptance page, and no matter what I do (accept, reject, reload the main url of the page) it keeps redirecting to the acceptance page. 
If I access to my database and check the UserAgreements the object is there.
And if I reload the server it stop doing that and starts working as expected (detecting that the user is accepted).

If you need more info about it that could help please ask for it.

**Comment by goromachine** [comment]
This seems to be working since I fixed the translation issue.
