### ISSUE TITLE
django3.0 support

### ISSUE THREAD

**Issue by hhummel** [revsys/django-tos#45]
`django.shortcuts.render_to_response` was deprecrated jn django3.0 so lhat line 11 in views.py throws an error. Any plans to support v3.0?

**Comment by nicholasserra** [comment]
Yup shouldn't be a big deal. Can easily wire it into compat.py. PRs welcome, otherwise i'll add this to my queue and knock it out eventually.

**Comment by hhummel** [comment]
I took a crack at it. Thanks for the quick response!

**Comment by hhummel** [comment]
Better have django 3 in Travis! Took a shot at that too

**Comment by occamssafetyrazor** [comment]
@nicholasserra can the Pypi package be updated to include this change? I ran pip install django-tos and it's an older commit where views.py imports render_to_response and it throws an error in Django 3
For now, I'll try installing from this specific commit. Thanks for all your work! And thanks @hhummel for the Django 3 compatibility update.

**Comment by nicholasserra** [comment]
@frankwiles can we get a new version and pypi release for this django compat? Thanks!

cc @occamssafetyrazor
