### ISSUE TITLE
Pypi Package supporting Python 3 and up

### ISSUE THREAD

**Issue by floese** [revsys/django-tos#67]
Hi and thanks for your work on this.
Are there any plans to release the python >= 3 supporting code of this respository in a pypi package? Or are there reasons that this hasn't happened? As I'd imagine it to be more comfortable for users of this package to be able to include it to a project by using a official pip installable release.

**Comment by frankwiles** [comment]
I'm confused, the version that is released support Python 3.  In fact, it's currently only tested against Python 3.7 - 3.10 https://github.com/revsys/django-tos/blob/master/.github/workflows/django.yml#L15-L42

**Comment by floese** [comment]
Thanks for getting back.
I just installed the django-tos package v1.0.0 via pip to retest. There's an occurence of unicode() in models.py (line 76) which is deprecated since Python 3.0. This leads to an error when (e.g.) trying to access the User Agreements Model in the django admin site. 
In the master branch of this repository this has been fixed in December 2022. The latest release on pypi seems to be from February 2022.

**Comment by nicholasserra** [comment]
Ah, makes sense. Probably don't have test coverage hitting that line.

@frankwiles looks like we need a version bump and pypi release of the latest changes on github whenever you have a moment, and we should be good to go

**Comment by nicholasserra** [comment]
Thanks! Do you have a commit pending with the version bump?

**Comment by frankwiles** [comment]
Yes, good catch.  I committed it but forgot to push when I got distracted by the next shiny object. It's there now.
