### ISSUE TITLE
Usage of the middleware can prevent static files to be served.

### ISSUE THREAD

**Issue by Hopiu** [revsys/django-tos#69]
Dear maintainer of the django-tos package,

Thank you for your efforts in maintaining this package. It's much appreciated.

I have a question regarding its use in conjunction with serving static files through Django. I've noticed that it blocks the delivery of stylesheets, images, fonts, etc., which results in an unstyled Terms of Service page.

Is there a recommended way to handle this issue? I would greatly appreciate any guidance you can provide. For now, I just reimplemented the middleware. For now, I am extending the middleware to fast skip certain file types.

I understand that many users do not experience this issue as they serve their static files through a web server. However, I still believe that it could be desirable to have a "fast skip" rule for static and media files.

If this is something you would find useful, I would be happy to prepare a pull request to add this functionality. Please let me know if this is of interest to you.

Thank you again for your work on this package.

Best regards,
Benedikt

**Comment by nicholasserra** [comment]
Hello,

What do you mean it's blocking stylesheets? Shouldn't be anything in here affecting static media.

Most people run collectstatic and serve the static media independetly via nginx or a CDN.

**Comment by Hopiu** [comment]
In our development environment, Django serves all files. However, the static and media files on the Terms of Service page are blocked by the `UserAgreementMiddleware`. It would be helpful if there was an easy way to bypass the check for files under `STATIC_URL`  and `MEDIA_URL`.

**Comment by frankwiles** [comment]
Are you using whitenoise (or something similar) to serve your static media in your production environment maybe?

**Comment by nicholasserra** [comment]
So, did a little more digging.

In development, with the staticfiles app in INSTALLED_APPS, and when running `runserver`, django automatically excludes static media from running through the middleware. 

So in dev via runserver, django doesn't run static files through the MIDDLEWARE.

Only way it should be blocking is if you're not running the django staticfiles middleware. 

https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#runserver

Also, in dev, it's common to add the staticfiles url for staticfiles routing:

https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#static-file-development-view

Not sure if BOTH are required for serving locally, but everything i've ever worked on in Django has always had that url wired into an environment check.

So, I think this package is performing as intended, routing all requests through the middleware. Static media requests, as you mentioned, shouldn't be ran through django in prod.

In development, if configured right, this middleware shouldn't even be seeing static files.

My guess is there's some misconfiguration with how you have staticfiles set up locally that's causing the routing issue.

Gonna close for now as I don't think we need any code patch here related to this.
