### ISSUE TITLE
NoActiveTermsOfService

### ISSUE THREAD

**Issue by eljeffeg** [revsys/django-tos#80]
Thanks for the middleware - appreciate it.  One note, as we tend to rebuild our containers for dev often and I get hit with this.

NoActiveTermsOfService at /terms-of-service/confirm/
['Please create an active Terms-of-Service']

Does this really need to raise an exception and prevent accessing the site?  Wouldn't logging an error or warning be sufficient and just let the user login / redirect as normal?  Doing the TOS update_terms is not part of the normal initialization as we don't want to reset this every time.

**Comment by nicholasserra** [comment]
Could probably wire in a setting to toggle this behavior

**Comment by frankwiles** [comment]
I **think** my/our original thinking was if you were using this you REALLY wanted to be sure the users were agreeing to a TOS and the absence of one should really be a failure.  But I agree, a setting where you could control this behavior makes sense to me!

**Comment by eljeffeg** [comment]
Alternatively, is there a way I could check if it exists in my startup settings and then issue the command to add it if it doesn't?

**Comment by blag** [comment]
Hi, [original author of the middleware](https://github.com/revsys/django-tos/pull/21) here.

I think it might be reasonable to simply check `settings.DEBUG` and issue a warning if that's `True`, and keep the current behavior of raising an exception when running in production.

The intent to fail loudly is still valid in production IMO. But relaxing that for development is also valid and reasonable.

If this is acceptable to everybody, I have implemented this in PR #84.
